COMP: Simplify directory listing using vtksys::Directory
NIRALUser/RigidAlignment pull request #9
Opened 2022-08-02 22:04 UTC by jcfr

2022-08-03 12:30 UTC, Connor-Bowley requested changes

2022-08-03 12:30 UTC, Connor-Bowley commented on RigidAlignment.cxx
> +    if(filename.find(suffix) != string::npos && filename.find_last_of(suffix) == filename.size() - 1)
I don't think the logic here is actually correct (the original logic, which your change replicates).

`std::string::find_last_of` has the following semantics (from https://en.cppreference.com/w/cpp/string/basic_string/find_last_of)

> Finds the last character equal to **_one of_** characters in the given character sequence.

The current use of this is `if(! getListFile(landmark.c_str(), landmarkList, "fcsv"))` which makes it seem like we are looking for a `.fcsv` file, but in reality a `.mov` file would incorrectly match.

I think this needs to change to use something like `std::string::rfind` instead.

2022-08-03 12:30 UTC, Connor-Bowley commented on RigidAlignment.cxx
> +  sort(list.begin(), list.begin() + list.size());
If we are changing things anyway can we switch this to be `sort(list.begin(), list.end())` to be more idiomatic and clear we are sorting the whole list.

2022-08-30 15:17 UTC, Connor-Bowley commented on RigidAlignment.cxx
> +    if(filename.find(suffix) != string::npos && filename.find_last_of(suffix) == filename.size() - 1)
I have updated this to be correct (although it doesn't use rfind, as that is more inefficient than necessary).

2022-08-30 15:17 UTC, Connor-Bowley approved these changes

2022-08-30 15:20 UTC, merged

2022-08-30 15:33 UTC, jcfr commented
Thanks for helping out with this 🙏